export const awardList = [
  { x: 0, y: 0, index: 1, src: '', activeSrc: '' },
  { x: 1, y: 0, index: 2, src: '', activeSrc: '' },
  { x: 2, y: 0, index: 3, src: '', activeSrc: '' },
  { x: 3, y: 0, index: 4, src: '', activeSrc: '' },
  { x: 4, y: 0, index: 5, src: '', activeSrc: '' },
  {
    x: 5,
    y: 0,
    index: 1,
    src: require('./img/czz_img_01_unsel.png'),
    activeSrc: require('./img/czz_img_01_sel.png'),
  },
  {
    x: 5,
    y: 1,
    index: 2,
    src: require('./img/czz_img_02_unsel.png'),
    activeSrc: require('./img/czz_img_02_sel.png'),
  },
  { x: 4, y: 1, index: 6, src: '', activeSrc: '' },
  { x: 3, y: 1, index: 7, src: '', activeSrc: '' },
  { x: 2, y: 1, index: 8, src: '', activeSrc: '' },
  { x: 1, y: 1, index: 9, src: '', activeSrc: '' },
  { x: 0, y: 1, index: 10, src: '', activeSrc: '' },
  { x: 0, y: 2, index: 11, src: '', activeSrc: '' },
  { x: 1, y: 2, index: 12, src: '', activeSrc: '' },
  { x: 2, y: 2, index: 13, src: '', activeSrc: '' },
  { x: 3, y: 2, index: 14, src: '', activeSrc: '' },
  { x: 4, y: 2, index: 15, src: '', activeSrc: '' },
  {
    x: 5,
    y: 2,
    index: 3,
    src: require('./img/czz_img_03_unsel.png'),
    activeSrc: require('./img/czz_img_03_sel.png'),
  },
  {
    x: 5,
    y: 3,
    index: 4,
    src: require('./img/czz_img_04_unsel.png'),
    activeSrc: require('./img/czz_img_04_sel.png'),
  },
  { x: 4, y: 3, index: 16, src: '', activeSrc: '' },
  { x: 3, y: 3, index: 17, src: '', activeSrc: '' },
  { x: 2, y: 3, index: 18, src: '', activeSrc: '' },
  { x: 1, y: 3, index: 19, src: '', activeSrc: '' },
  { x: 0, y: 3, index: 20, src: '', activeSrc: '' },
  { x: 0, y: 4, index: 21, src: '', activeSrc: '' },
  { x: 1, y: 4, index: 22, src: '', activeSrc: '' },
  { x: 2, y: 4, index: 23, src: '', activeSrc: '' },
  { x: 3, y: 4, index: 24, src: '', activeSrc: '' },
  { x: 4, y: 4, index: 25, src: '', activeSrc: '' },
  {
    x: 5,
    y: 4,
    index: 5,
    src: require('./img/czz_img_05_unsel.png'),
    activeSrc: require('./img/czz_img_05_sel.png'),
  },
  {
    x: 5,
    y: 5,
    index: 6,
    src: require('./img/czz_img_06_unsel.png'),
    activeSrc: require('./img/czz_img_06_sel.png'),
  },
  {
    x: 4,
    y: 5,
    index: 7,
    src: require('./img/czz_img_07_unsel.png'),
    activeSrc: require('./img/czz_img_07_sel.png'),
  },
  {
    x: 3,
    y: 5,
    index: 8,
    src: require('./img/czz_img_08_unsel.png'),
    activeSrc: require('./img/czz_img_08_sel.png'),
  },
  {
    x: 2,
    y: 5,
    index: 9,
    src: require('./img/czz_img_09_unsel.png'),
    activeSrc: require('./img/czz_img_09_sel.png'),
  },
  {
    x: 1,
    y: 5,
    index: 10,
    src: require('./img/czz_img_10_unsel.png'),
    activeSrc: require('./img/czz_img_10_sel.png'),
  },
  {
    x: 0,
    y: 5,
    index: 11,
    src: require('./img/czz_img_11_unsel.png'),
    activeSrc: require('./img/czz_img_11_sel.png'),
  },
];
